[package]
name = "advent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "1a"
path = "src/1a.rs"

[[bin]]
name = "1b"
path = "src/1b.rs"
[dependencies]
